name: Build and Run Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install llvm-dev
    - name: Build and run plugin
      run: make test CXXFLAGS="-I/usr/lib/llvm-18/include"
