name: Darwin Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: mac-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install llvm
    - name: Build and run plugin
      run: make test CXXFLAGS="-I/opt/homebrew/opt/llvm/include"
